# On pushes to main, build packages for all supported platforms. Then, create a Github Release and attach those
# binaries, then publish personal Orchid site.

name: 'Push to `main` (Create Release)'

on:
  push:
    branches: ['main']

jobs:
  buildSiteAndPushToGithubPages:
    runs-on: 'macos-latest'
    env:
      GITHUB_ACTOR: '${{ github.actor }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 11'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'temurin'
          java-version: 11
      - name: 'Build Kotlin Compose/Web SPA'
        run: './gradlew :app:build -Prelease'
      - name: 'Build the rest of the static site'
        run: './gradlew :site:run -Prelease'
      - name: 'Deploy to GitHub Pages'
        uses: 'JamesIves/github-pages-deploy-action@v4.4.0'
        with:
          folder: 'build/dist'
