# On pushes to main, build packages for all supported platforms. Then, create a Github Release and attach those
# binaries, then publish personal Orchid site.

name: 'Push to `main` (Create Release)'

on:
  push:
    branches: ['main']

jobs:
  buildPackagesOnAll:
    strategy:
      matrix:
        java: [16]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: 'Build ${{ matrix.os }} packages on JDK ${{ matrix.java }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'
      - name: 'Build packages with Gradle'
        run: './gradlew :tidal:designer-client-desktop:package'
      - name: 'Upload Tidal packages'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'tidal-${{ matrix.os }}'
          path: |
            tidal/designer-client-desktop/build/compose/binaries/main/**/*.dmg
            tidal/designer-client-desktop/build/compose/binaries/main/**/*.msi
            tidal/designer-client-desktop/build/compose/binaries/main/**/*.deb
          retention-days: 1
          if-no-files-found: 'error'

  createReleaseWithAllPackages:
    runs-on: 'macos-latest'
    needs: ['buildPackagesOnAll']
    env:
      GITHUB_ACTOR: '${{ github.actor }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'git fetch --prune --unshallow --tags'
      - name: 'Set up JDK 11'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'temurin'
          java-version: 11
      - name: 'Download Tidal packages from all OSs'
        uses: 'actions/download-artifact@v2'
        id: 'download'
        with:
          path: 'compose/binaries/main'
      - name: 'Create release with all packages'
        uses: 'softprops/action-gh-release@v1'
        with:
          files: '${{steps.download.outputs.download-path}}/**/*'
          tag_name: 'v0.3.1'
          target_commitish: 'main'
          fail_on_unmatched_files: true
          generate_release_notes: true
